"""fix created_at defaults

Revision ID: 0004
Revises: 0003
Create Date: 2026-05-27 16:50:00.000000+00:00

Migrations 0001 and 0002 declared timestamp columns via SQLAlchemy's
``server_default="now()"`` (a Python *string*). SQLAlchemy passes that
through verbatim, so Postgres saw ``DEFAULT 'now()'`` — a quoted literal
that PG implicitly casts to ``timestamptz`` **at table-create time**,
freezing the moment the migration ran into every row's default. Every
INSERT without an explicit value got that same frozen timestamp, breaking
any ``ORDER BY created_at`` because tie-breaking is implementation-defined.

This migration rewrites each affected column's default as an honest SQL
function expression (``DEFAULT now()``) so Postgres evaluates it per-INSERT.
The model source (``rehketo/db/models.py``) is corrected in the same commit
(``server_default=func.now()``) to prevent any future autogenerated migration
from re-introducing the bug.

Existing rows are NOT backfilled — their frozen timestamps cannot be
reconstructed reliably. Any conversation persisted before this migration
will continue to render in an undefined order; create a fresh conversation
to see correct ordering.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


# (table, column) for every default we created with the broken pattern.
# LangGraph's checkpointer tables (migration 0003) are managed upstream and
# are not in this list.
_COLUMNS: tuple[tuple[str, str], ...] = (
    ("users", "created_at"),
    ("identities", "created_at"),
    ("sessions", "created_at"),
    ("connections", "created_at"),
    ("conversations", "created_at"),
    ("conversations", "updated_at"),
    ("runs", "created_at"),
    ("messages", "created_at"),
    ("run_events", "created_at"),
)


def upgrade() -> None:
    for table, column in _COLUMNS:
        op.execute(f"ALTER TABLE {table} ALTER COLUMN {column} SET DEFAULT now()")


def downgrade() -> None:
    # Faithfully restore the pre-fix state so `alembic downgrade` reproduces
    # what migrations 0001-0002 created. Re-introduces the all-rows-same
    # timestamp bug — included for round-trip fidelity only; never downgrade
    # in any environment that captures new data.
    for table, column in _COLUMNS:
        op.execute(
            f"ALTER TABLE {table} ALTER COLUMN {column} "
            f"SET DEFAULT 'now()'::timestamp with time zone"
        )
