name: Python Lint

on:
  push:
    branches: [main, master, dev*]
  pull_request:
    branches: [main, master, dev*]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"
      - uses: astral-sh/ruff-action@v3
        with:
          args: "check -v" 

  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: "auto"
      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run mypy
        run: uv run mypy rehketo --ignore-missing-imports --no-error-summary || true
